project:
  type: website
  output-dir: docs

website:
  title: "Essays"
  navbar:
    right:
    #  - about.qmd
      - text: hfwu
        href: https://www.hfwu.de/jan-vosswinkel/
      - icon: github
        href: https://github.com/janvoss
      - icon: linkedin
        href: www.linkedin.com/in/jan-s-voßwinkel-a6
      - icon: twitter-x
        href: https://x.com/JanSVosswinkel
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: source

